const miningAreas = [
  {
    name: "Jharia Coalfield",
    coords: [23.775, 86.42],
    mineral: "Coal",
    color: "#1c1c1c",
    reason: "Largest coalfield in India; extensive coking coal reserves, major mining hub for steel and energy industries.",
  },
  {
    name: "Bokaro Coal Mine",
    coords: [23.67, 86.15],
    mineral: "Coal",
    color: "#2c2c2c",
    reason: "Major coalfield; hosts both old and newly proposed mines (Parbatpur Central, Chandragupta OCP).",
  },
  {
    name: "Ramgarh Coalfield",
    coords: [23.63, 85.52],
    mineral: "Coal",
    color: "#383838",
    reason: "Active coal mining area supporting thermal energy plants; CCL operations.",
  },
  {
    name: "North Karanpura Coalfield",
    coords: [23.89, 85.17],
    mineral: "Coal",
    color: "#454545",
    reason: "Contains new mines (Kotre Basantpur, Gondulpara Block); rapid expansion since 2025.",
  },
  {
    name: "South Karanpura Coalfield",
    coords: [23.82, 84.93],
    mineral: "Coal",
    color: "#505050",
    reason: "Active coal mining has resumed here; part of CCL's expanded operations.",
  },
  {
    name: "Chandrapura Coal Mine",
    coords: [23.75, 86.08],
    mineral: "Coal",
    color: "#606060",
    reason: "Integrated with Bokaro coalfields; major surface and underground mining.",
  },
  {
    name: "Pakri Barwadih Coal Mine",
    coords: [23.91, 85.54],
    mineral: "Coal",
    color: "#707070",
    reason: "One of India’s largest open-cast coal mines; operated by NTPC.",
  },
  {
    name: "Rajmahal Coalfield",
    coords: [25.09, 87.39],
    mineral: "Coal",
    color: "#808080",
    reason: "Located on Jharkhand–West Bengal border; significant coal mining area for power plants.",
  },
  {
    name: "Giridih Coalfield",
    coords: [24.19, 86.30],
    mineral: "Coal",
    color: "#888888",
    reason: "Oldest coal mining region in India; intermittent continued operations.",
  },
  {
    name: "Daltonganj (Auranga area)",
    coords: [24.05, 84.07],
    mineral: "Coal",
    color: "#999999",
    reason: "Mining revived recently, with regional emphasis on open-cast mining.",
  },
  {
    name: "Latehar (Banhardi Block)",
    coords: [23.77, 84.50],
    mineral: "Coal",
    color: "#aaaaaa",
    reason: "Geologically proven block; allocated to Jharkhand State Electricity Board for mining.",
  },
  {
    name: "Chuperbhita & Pachwara Coal Mines",
    coords: [25.05, 87.25],
    mineral: "Coal",
    color: "#bbbbbb",
    reason: "Eastern Jharkhand mining blocks actively auctioned and operated.",
  }
];
